# ExpansionHunter Denovo PBS script
#
#PBS -N EHDN_RepeatExpansions
#PBS
#PBS -t 0-119       # 120 BAM files
#PBS -V

#PBS -l nodes=1:ppn=1
#PBS -l mem=2gb
#PBS -l walltime=8:00:00

#PBS -m a
#PBS -M bennett.ma@wehi.edu.au


BAM_FILES=( /stornext/HPCScratch/lab_bahlo/Illumina_Polaris/RepeatExpansions/*.bam )

OUTPUT_DIR=/stornext/HPCScratch/lab_bahlo/Illumina_Polaris/data/ExpansionHunterDenovo_v0.8.0/RepeatExpansions

REFERENCE=/stornext/HPCScratch/lab_bahlo/Illumina_Polaris/reference/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa

# ---------------------------------------------------------------------------------------

EHDN=/stornext/HPCScratch/lab_bahlo/Illumina_Polaris/ExpansionHunterDenovo_0.8.0/ExpansionHunterDenovo

mkdir -p $OUTPUT_DIR

# Run ExpansionHunter Denovo

BAM="${BAM_FILES[$PBS_ARRAYID]}"

BASE=$(basename $BAM ".bam")

$EHDN profile --reads $BAM --reference $REFERENCE --output-prefix $OUTPUT_DIR/$BASE



